name: Non regression tests for Zipper
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  #############################################################################
  ### Linux
  #############################################################################
  non_regression_linux:
    name: Non regression on Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Zipper
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config lcov libdw-dev
      - name: Download, configure and install Google test
        run: |
          wget https://github.com/google/googletest/archive/release-1.11.0.tar.gz
          tar xf release-1.11.0.tar.gz
          cd googletest-release-1.11.0
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .
          sudo make install
      - name: Build Zipper
        run: |
          make download-external-libs
          make compile-external-libs
          make -j`nproc --all`
      - name: Installation
        run: |
          sudo make install
      - name: Non regression
        run: |
          cd tests
          make -j`nproc --all`
          ./build/Zipper-UnitTest

  #############################################################################
  ### MacOS X
  #############################################################################
  non_regression_macos:
    name: Non regression on MacOS X
    runs-on: macos-latest
    steps:
      - name: Checkout Zipper
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install system packages
        run: |
          brew install pkg-config
      - name: Download, configure and install Google test
        run: |
          wget https://github.com/google/googletest/archive/release-1.11.0.tar.gz
          tar xf release-1.11.0.tar.gz
          cd googletest-release-1.11.0
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .
          sudo make install
      - name: Build Zipper
        run: |
          make download-external-libs
          make compile-external-libs
          make -j`nproc --all`
      - name: Non regression
        run: |
          cd tests
          make -j`nproc --all`
          ./build/Zipper-UnitTest
